### ISSUE TITLE
Refactor: 로그인시 nullpointerException 해결, 장바구니 리스트 조회 코드 수정, PUBLIC_URLS 추가 

### ISSUE THREAD

**Issue by WONSEOKJE** [KDT3-MiniProject-8/MiniProject-BE#44]
## Description(설명)

로그인 기능은 잘되었으나 로그에 nullpointerException 에러를 발견
장바구니 리스트 조회 시 카테고리명만 같으면 다른 멤버의 리스트도 조회되는 에러를 발견
아이디 중복확인 url이 PUBLIC_URLS에 추가되어 있지 않음

## Tasks(New feature)
- [x] 로그인시 nullpointerException 해결
- [x] 장바구니 리스트 조회 코드 수정
- [x] PUBLIC_URLS 추가
