### ISSUE TITLE
Feat: 프론트 요청사항 추가 - 로그인시 이름 추가, 관심상품 유/무 확인, 신청한 상품 갯수 API

### ISSUE THREAD

**Issue by dkschdcks** [KDT3-MiniProject-8/MiniProject-BE#57]
## Description(설명)
- 로그인시 반환값에 멤버 이름 추가
- 상세페이지 클릭시 관심상품에 등록 했는지 확인 기능 구현
- 구매(신청)한 상품 갯수 확인하는 API 구현 

## Tasks(New feature)
- [x] MemberServiceImpl에서 getName메소드 사용해서 구현
- [x] 관심상품 유/무 boolean으로 확인해서 해당 값 PurchaseResponseDTO에 추가
- [x] 상품 갯수 확인 API : 
         1. GetMapping 
         2. URL : /count_purchase
         3. header > memberId로 찾기

## References
제가 다르게 해석한 부분 말씀해주세요~~~
